chg:pkg: Add grpcio-tools to top to get latest version.
This leaves two unresolvable problems (upper version conflicts):
ERROR: mediafire 0.6.0 has requirement requests<=2.11.1,>=2.4.1, but
you'll have requests 2.27.1 which is incompatible.
ERROR: python-novaclient 2.27.0 has requirement pbr<2.0,>=1.6, but
you'll have pbr 5.8.1 which is incompatible.

[skip ci]