Remove python-cloudfiles from suggestions
This dependency cannot be installed on Python 3:

```
#12 19.82   Downloading python-cloudfiles-1.7.11.tar.gz (330 kB)
#12 20.00     ERROR: Command errored out with exit status 1:
#12 20.00      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2iwvh4bp/python-cloudfiles/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2iwvh4bp/python-cloudfiles/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b1gvstfs
#12 20.00          cwd: /tmp/pip-install-2iwvh4bp/python-cloudfiles/
#12 20.00     Complete output (9 lines):
#12 20.00     Traceback (most recent call last):
#12 20.00       File "<string>", line 1, in <module>
#12 20.00       File "/tmp/pip-install-2iwvh4bp/python-cloudfiles/setup.py", line 6, in <module>
#12 20.00         from cloudfiles.consts import __version__
#12 20.00       File "/tmp/pip-install-2iwvh4bp/python-cloudfiles/cloudfiles/__init__.py", line 82, in <module>
#12 20.00         from cloudfiles.connection     import Connection, ConnectionPool
#12 20.00       File "/tmp/pip-install-2iwvh4bp/python-cloudfiles/cloudfiles/connection.py", line 13, in <module>
#12 20.00         from    urllib    import urlencode
#12 20.00     ImportError: cannot import name 'urlencode' from 'urllib' (/usr/local/lib/python3.8/urllib/__init__.py)
#12 20.00     ----------------------------------------
#12 20.00 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Also, it is no longer supported. Rackspace uses `pyrax` nowadays. Removing to avoid confusions.